### ISSUE TITLE
HTML ISSUE 1  -- Give a proper structure to the file. Make it more readable, add proper indentation.

### ISSUE THREAD

**Issue by caro-oviedo** [caro-oviedo/SheepCounter_JS_HTML_CSS_CodeNewbies_Hacktoberfest_2021#2]
Go to **index.html**  and JUST modify ISSUE 1. If you submit a PR modiifying another part of the file IT WILL NOT BE ACCEPTED.

**Comment by shikhar13012001** [comment]
I would like to work on this , Could you assign it to me ?

**Comment by kushwahajai74** [comment]
i would like to learn about git and github by doing, so can you assign this to me.
