### ISSUE TITLE
JavaScript Issue 2

### ISSUE THREAD

**Issue by caro-oviedo** [caro-oviedo/SheepCounter_JS_HTML_CSS_CodeNewbies_Hacktoberfest_2021#6]
Go to apps.js and JUST modify ISSUE 2. If you submit a PR modiifying another part of the file IT WILL NOT BE ACCEPTED.
[https://github.com/caro-oviedo/SheepCounter_JS_HTML_CSS_CodeNewbies_Haacktoberfest_2021](url)

**Comment by shikhar13012001** [comment]
I would like to work on this , Could you assign it to me ?

**Comment by shikhar13012001** [comment]
Could you add hacktoberfest-accepted label to the PR?
